### ISSUE TITLE
Copy/paste/adapt examples from the `db-postgres` README to `db-mariadb`'s README

### ISSUE THREAD

**Issue by postmodern** [socketry/db-mariadb#3]
[db-postgres](https://github.com/socketry/db-postgres?tab=readme-ov-file#1-usage) has extensive examples in it's README on how to use the gem. I think those could be copy/pasted/adapted to `db-mariadb`.

**Comment by postmodern** [comment]
I would try to do this myself, but the Postgres examples contain Postgres-specific things that probably won't map 1:1 to MySQL/MariaDB. Also, there's *a lot* of examples to copy over; which is a good thing technically.

**Comment by ioquatix** [comment]
I think we should move all this documentation up into the `db` gem. It should mostly be driver/adapter agnostic.

**Comment by postmodern** [comment]
Sure. Although I suspect developers will find the `db-mysql`, `db-postgres`, etc, gems first via Google Search, then realize there's a higher-level `db` gem that wraps around them and provides `DB::Client`.

**Comment by ioquatix** [comment]
Let's do our best to make sure it's clear that's the case - I've added links in the main readme files, but I can also add it to the getting started guide.
